### PR TITLE
Add statsd adapter

### PR DESCRIPTION
**Pull request by luxflux**
Hi

I started implementing an adapter for statsd. So far the code works in the tests... Going to test it now against a real daemon.

What do you think about the code? Are you willing to merge it?

regards
 raf

### CODE REVIEW

**Comment by luxflux** [comment]
bump

**Comment by ahawkins** [comment]
@luxflux thanks for this. I'll take a look at it soon.

**Comment by luxflux** [comment]
Hi, did you have had the time to check it? :)

**Comment by ahawkins** [comment]
Damn man! Sorry this took me so long. I'm going to merge this in with some minor changes.

**Comment by ahawkins** [comment]
Hey, check out master. I changed your code slightly and add examples to readme. If everything is cool, I'll release a new minor version.

**Comment by luxflux** [comment]
Hi, just tested it out. It works like a charm. Running it now with statsd-client: https://github.com/bvandenbos/statsd-client . So changing the statsd-implementation works as well :)

**Pull request merged**
